version: "3"

services:
  tracker_mapper:
    build: .
    ports:
      - "$API_PORT:$API_PORT"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
      - PORT=8080
  db:
    image: postgres:9.4
    env_file: .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"