version: "3"

services:
  tracker_mapper:
    build: .
    ports:
      - "$API_PORT:$API_PORT"
    command: bash -c 'npm start'
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:12345/tracker_mapper
      - PORT=8080
  db:
    image: postgres:9.4
    env_file: .env
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB